version: "3"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
      - ./series:/tv
      - ./download-client:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
