version: '3'
services:
  mssql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_SA_PASSWORD=Sa12345!'
    restart: always
    container_name: mssql_server
    volumes:
      - './var_opt_mssql:/var/opt/mssql'
      - './backups:/var/backups'
    networks:
      - net
    ports:
      - 1433:1433
    user: root
networks:
  net:
